name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate Changelog
        uses: github-changelog-generator-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
